name: Cron Lighthouse Report Generator

on:
  push:
    branches:
      - 'develop'


jobs:
  cron-lighthouse-report-generator:
    name: 'Cron Lighthouse Report Generator'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://opentemplatehub.com
          uploadArtifacts: true
          configPath: .github/lighthouserc.yml

      - name: Check for Changes
        run: |
          mv .lighthouseci/* docs/lighthouse
          if git diff --exit-code; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi

      - name: Git Commit and Push
        if: ${{ env.changes_exist == 'true' }}
        run: |
          git config --global user.email "98660390+oth-service-user@users.noreply.github.com"
          git config --global user.name "OTH Service User"
          git commit -am "Workflow/lighthouse report update"
          git push
